import type { NodeDef } from 'node-red';

/**
 * Configuration options available to users.
 */
export interface UserConfigurationOptions {
    outputTarget?: string;
    outputProperty?: string;
    deviceIp?: string;
}

/**
 * Configuration generated by the user in the editor.
 */
export interface UserConfiguration extends NodeDef, UserConfigurationOptions {}
